contract Foo {
    pub fn decode_static_complex(s: StaticComplex) -> StaticComplex {
        return s
    }

    pub fn decode_string_complex(s: StringComplex) -> StringComplex {
        return s
    }

    pub fn decode_bytes_complex(s: BytesComplex) -> BytesComplex {
        return s
    }

    pub fn decode_nested_dynamic_complex(s: NestedDynamicComplex) -> NestedDynamicComplex {
        return s
    }

    pub fn decode_static_complex_elem_array(arr: Array<StaticComplex, 3>) -> Array<StaticComplex, 3> {
        return arr
    }

    pub fn decode_dynamic_complex_elem_array(arr: Array<NestedDynamicComplex, 3>) -> Array<NestedDynamicComplex, 3> {
        return arr
    }
}

pub struct StaticInner {
    pub inner_x: i32
    pub inner_y: i32
}
    
pub struct StaticComplex {
    pub inner: StaticInner
    pub outer_x: i256
}
    
pub struct StringComplex {
    pub string: String<8>
    pub outer_x: i32
}
    
pub struct BytesComplex {
    pub bytes: Array<u8, 8>
    pub outer_x: i32
}

pub struct NestedDynamicComplex {
    pub bytes_complex: BytesComplex
    pub static_complex: StaticComplex
    pub string_complex: StringComplex
}