contract Foo {
    my_bool: bool
    my_string: String<5>

    pub fn bar(baz: u256) {
        assert baz > 5
    }

    pub fn revert_with_static_string(baz: u256) {
        assert baz > 5, "Must be greater than five"
    }

    pub fn revert_with(baz: u256, reason: String<1000>) {
        assert baz > 5, reason
    }

    pub fn assert_sto_bool(mut self) {
        self.my_bool = false
        assert self.my_bool
    }

    pub fn assert_sto_string_msg(mut self) {
        self.my_string = "hello"
        assert false, self.my_string.to_mem()
    }
}
