contract Foo:
    my_bool: bool
    my_string: String<5>

    pub def bar(baz: u256):
        assert baz > 5

    pub def revert_with_static_string(baz: u256):
        assert baz > 5, "Must be greater than five"

    pub def revert_with(baz: u256, reason: String<1000>):
        assert baz > 5, reason

    pub def assert_sto_bool():
        self.my_bool = false
        assert self.my_bool

    pub def assert_sto_string_msg():
        self.my_string = "hello"
        assert false, self.my_string.to_mem()
