contract Foo {
    my_num: u256

    pub fn add(a: u256, b: u256) -> u256 {
        let mut v: u256 = a
        v += b
        return v
    }

    pub fn sub(a: u256, b: u256) -> u256 {
        let mut v: u256 = a
        v -= b
        return v
    }

    pub fn mul(a: u256, b: u256) -> u256 {
        let mut v: u256 = a
        v *= b
        return v
    }

    pub fn div(a: u256, b: u256) -> u256 {
        let mut v: u256 = a
        v /= b
        return v
    }

    pub fn mod(a: u256, b: u256) -> u256 {
        let mut v: u256 = a
        v %= b
        return v
    }

    pub fn pow(a: u256, b: u256) -> u256 {
        let mut v: u256 = a
        v **= b
        return v
    }

    pub fn lshift(a: u8, b: u8) -> u8 {
        let mut v: u8 = a
        v <<= b
        return v
    }

    pub fn rshift(a: u8, b: u8) -> u8 {
        let mut v: u8 = a
        v >>= b
        return v
    }

    pub fn bit_or(a: u8, b: u8) -> u8 {
        let mut v: u8 = a
        v |= b
        return v
    }

    pub fn bit_xor(a: u8, b: u8) -> u8 {
        let mut v: u8 = a
        v ^= b
        return v
    }

    pub fn bit_and(a: u8, b: u8) -> u8 {
        let mut v: u8 = a
        v &= b
        return v
    }

    pub fn add_from_sto(mut self, a: u256, b: u256) -> u256 {
        self.my_num = a
        self.my_num += b
        return self.my_num
    }

    pub fn add_from_mem(a: u256, b: u256) -> u256 {
        let mut my_array: Array<u256, 10> = [0; 10]
        my_array[7] = a
        my_array[7] += b
        return my_array[7]
    }
}
