use std::context::Context

contract Foo {
    my_num: u256

    pub fn baz(ctx: Context) -> u256 {
        return ctx.block_number()
    }

    pub fn bing(self, _ new_num: u256) -> u256 {
        self.my_num = new_num
        return self.my_num
    }
}

contract Bar {
    pub fn call_baz(ctx: Context, foo_addr: address) -> u256 {
        let foo: Foo = Foo(foo_addr)
        return foo.baz(ctx)
    }

    pub fn call_bing(ctx: Context) -> u256 {
        let foo: Foo = Foo.create(ctx, 0)
        return foo.bing(42)
    }
}
