use std::evm
use std::buf::{
    MemoryBuffer,
    MemoryBufferWriter
}
contract Foo {
    pub fn __call__() {
        unsafe {
            let ctx: Context = Context()
            let value: u256 = u256(bar(ctx))
            let mut buf: MemoryBuffer = MemoryBuffer::new(len: 32)
            let mut writer: MemoryBufferWriter = buf.writer()
            writer.write(value)
            evm::return_mem(buf)
        }
    }

    fn bar(ctx: Context) -> address {
        return ctx.self_address()
    }
}
