contract Foo:
    event Nums:
        idx num1: u256
        num2: u256

    event Bases:
        num: u256
        addr: address

    event Mix:
        num1: u256
        idx addr: address
        num2: u256
        my_bytes: u8[100]

    event Addresses:
        addrs: address[2]

    pub def emit_nums():
        emit Nums(num1=26, num2=42)

    pub def emit_bases(addr: address):
        emit Bases(num=26, addr)

    pub def emit_mix(addr: address, my_bytes: u8[100]):
        emit Mix(num1=26, addr, num2=42, my_bytes)

    pub def emit_addresses(addr1: address, addr2: address):
        addrs: address[2]
        addrs[0] = addr1
        addrs[1] = addr2
        emit Addresses(addrs)