pub struct Nums {
    #indexed
    pub num1: u256
    pub num2: u256
}

pub struct Bases {
    pub num: u256
    pub addr: address
}

pub struct Mix {
    pub num1: u256
    #indexed
    pub addr: address
    pub num2: u256
    pub my_bytes: Array<u8, 100>
}

pub struct Addresses {
    pub addrs: Array<address, 2>
}

contract Foo {

    pub fn emit_nums(ctx: Context) {
        ctx.emit(Nums(num1: 26, num2: 42))
    }

    pub fn emit_bases(ctx: Context, addr: address) {
        ctx.emit(Bases(num: 26, addr))
    }

    pub fn emit_mix(ctx: Context, addr: address, my_bytes: Array<u8, 100>) {
        ctx.emit(Mix(num1: 26, addr, num2: 42, my_bytes))
    }

    pub fn emit_addresses(ctx: Context, addr1: address, addr2: address) {
        let addrs: Array<address, 2> = [address(0); 2]
        addrs[0] = addr1
        addrs[1] = addr2
        ctx.emit(Addresses(addrs))
    }
}
