contract Foo:
    event MyEvent:
        my_num: u256
        my_addrs: address[5]
        my_string: String<11>

    pub def emit_event(my_num: u256, my_addrs: address[5], my_string: String<11>):
        emit MyEvent(my_num, my_addrs, my_string)

    pub def build_array(a: u256, b: u256) -> u256[3]:
        let my_array: u256[3]
        my_array[0] = a
        my_array[1] = a * b
        my_array[2] = b
        return my_array

contract FooProxy:
    pub def call_emit_event(
        foo_address: address,
        my_num: u256,
        my_addrs: address[5],
        my_string: String<11>
    ):
        let foo: Foo = Foo(foo_address)
        foo.emit_event(my_num, my_addrs, my_string)

    pub def call_build_array(
         foo_address: address,
         a: u256,
         b: u256,
    ) -> u256[3]:
        let foo: Foo = Foo(foo_address)
        return foo.build_array(a, b)
