struct MyEvent {
    pub my_num: u256
    pub my_addrs: Array<address, 5>
    pub my_string: String<11>
}

contract Foo {

    pub fn emit_event(self, mut ctx: Context, my_num: u256, my_addrs: Array<address, 5>, my_string: String<11>) {
        ctx.emit(MyEvent(my_num, my_addrs, my_string))
    }

    pub fn build_array(self, a: u256, b: u256) -> Array<u256, 3> {
        let mut my_array: Array<u256, 3> = [0; 3]
        my_array[0] = a
        my_array[1] = a * b
        my_array[2] = b
        return my_array
    }

    pub fn pure_add(_ x: u256, _ y: u256) -> u256 {
        return x + y
    }
}

contract FooProxy {
    pub fn call_emit_event(mut ctx: Context, foo_address: address, my_num: u256, my_addrs: Array<address, 5>, my_string: String<11>) {
        let foo: Foo = Foo(foo_address)
        foo.emit_event(ctx, my_num, my_addrs, my_string)
    }

    pub fn call_build_array(foo_address: address, a: u256, b: u256) -> Array<u256, 3> {
        let foo: Foo = Foo(foo_address)
        return foo.build_array(a, b)
    }

    pub fn add(_ x: u256, _ y: u256) -> u256 {
        return Foo::pure_add(x, y)
    }
}
