contract Foo {
    pub fn bar() -> u256 {
        let mut my_array: Array<u256, 5> = [0; 5]
        my_array[0] = 2
        my_array[1] = 3
        my_array[2] = 5
        my_array[3] = 6
        my_array[4] = 9
        let mut sum: u256 = 0
        for i in my_array {
            if i % 2 == 0 {
                continue
            }
            sum = sum + i
        }
        return sum
    }
}
