contract Foo {
    my_bool1: bool
    my_bool2: bool
    my_bool3: bool

    pub fn bar(mut self) -> u256 {
        self.my_bool1 = false
        self.my_bool2 = false
        self.my_bool3 = true
        if self.my_bool1 {
            return 26
        }
        if self.my_bool2 {
            return 26
        }
        if self.my_bool3 {
            return 42
        }
        return 26
    }
}
