contract Intrinsics {
    pub fn add(x: u256, y: u256) -> u256 {
        unsafe {
            return __add(x, y)
        }
    }

    pub fn gas() -> u256 {
        unsafe {
            return __gas()
        }
    }

    pub fn addr() -> address {
        unsafe {
            return address(__address())
        }
    }

    pub fn self_balance() -> u256 {
        unsafe {
            return __selfbalance()
        }
    }

    pub fn other_balance(a: u256) -> u256 {
        unsafe {
            return __balance(a)
        }
    }

    pub fn caller() -> address {
        unsafe {
            return address(__caller())
        }
    }

    pub fn callvalue() -> u256 {
        unsafe {
            return __callvalue()
        }
    }

    pub fn calldataload(offset: u256) -> u256 {
        unsafe {
            return __calldataload(offset)
        }
    }

    pub fn calldatasize() -> u256 {
        unsafe {
            return __calldatasize()
        }
    }

    pub fn calldatacopy(offset: u256, len: u256) -> u256 {
        unsafe {
            __calldatacopy(0, offset, len)
            return __mload(0)
        }
    }

    pub fn codesize() -> u256 {
        unsafe {
            return __codesize()
        }
    }

    pub fn extcodesize(addr: u256) -> u256 {
        unsafe {
            return __extcodesize(addr)
        }
    }

    pub fn extcodehash(addr: u256) -> u256 {
        unsafe {
            return __extcodehash(addr)
        }
    }

    pub fn chainid() -> u256 {
        unsafe {
            return __chainid()
        }
    }

    pub fn basefee() -> u256 {
        unsafe {
            return __basefee()
        }
    }

    pub fn origin() -> u256 {
        unsafe {
            return __origin()
        }
    }

    pub fn gasprice() -> u256 {
        unsafe {
            return __gasprice()
        }
    }

    pub fn blockhash(n: u256) -> u256 {
        unsafe {
            return __blockhash(n)
        }
    }

    pub fn coinbase() -> u256 {
        unsafe {
            return __coinbase()
        }
    }

    pub fn timestamp() -> u256 {
        unsafe {
            return __timestamp()
        }
    }

    pub fn number() -> u256 {
        unsafe {
            return __number()
        }
    }

    pub fn difficulty() -> u256 {
        unsafe {
            return __prevrandao()
        }
    }

    pub fn gaslimit() -> u256 {
        unsafe {
            return __gaslimit()
        }
    }
}
