type MY_ARRAY = Array<bool, { C4 }>

const C1: i32 = 1
const C2: i32 = C1 * 3
const C3: i32 = C4 + 2
const C4: i32 = 42

contract Foo {
    fn bar() -> i32 {
        const LOCAL_CONST: i32 = C3 * 2
        let _arr1: Array<i32, { C2 }> = [i32(0); { C2 }]
        let _arr2: Array<i32, { LOCAL_CONST }> = [i32(0); { LOCAL_CONST }]
        let _my_array: MY_ARRAY = [true; { C4 }]
        return C4
    }
}
