use std::traits::{Min, Max}

const I8_MIN: i8 = -128
const I8_MAX: i8 = 127
const U8_MIN: u8 = 0
const U8_MAX: u8 = 255

const I16_MIN: i16 = -32768
const I16_MAX: i16 = 32767
const U16_MIN: u16 = 0
const U16_MAX: u16 = 65535

const I32_MIN: i32 = -2147483648
const I32_MAX: i32 = 2147483647
const U32_MIN: u32 = 0
const U32_MAX: u32 = 4294967295

const I64_MIN: i64 = -9223372036854775808
const I64_MAX: i64 = 9223372036854775807
const U64_MIN: u64 = 0
const U64_MAX: u64 = 18446744073709551615

const I128_MIN: i128 = -170141183460469231731687303715884105728
const I128_MAX: i128 = 170141183460469231731687303715884105727
const U128_MIN: u128 = 0
const U128_MAX: u128 = 340282366920938463463374607431768211455

const I256_MIN: i256 = -57896044618658097711785492504343953926634992332820282019728792003956564819968
const I256_MAX: i256 = 57896044618658097711785492504343953926634992332820282019728792003956564819967
const U256_MIN: u256 = 0
const U256_MAX: u256 = 115792089237316195423570985008687907853269984665640564039457584007913129639935


contract Foo {
    pub fn assert_min_max() {
        assert u8::min() == U8_MIN
        assert u16::min() == U16_MIN
        assert u32::min() == U32_MIN
        assert u64::min() == U64_MIN
        assert u128::min() == U128_MIN
        assert u256::min() == U256_MIN
        // TODO: Investigate why these can't be compared against their const values
        assert i8::min() == get_i8_const_min()
        assert i16::min() == get_i16_const_min()
        assert i32::min() == get_i32_const_min()
        assert i64::min() == get_i64_const_min()
        assert i128::min() == get_i128_const_min()
        assert i256::min() == get_i256_const_min()

        assert u8::max() == U8_MAX
        assert u16::max() == U16_MAX
        assert u32::max() == U32_MAX
        assert u64::max() == U64_MAX
        assert u128::max() == U128_MAX
        assert u256::max() == U256_MAX

        assert i8::max() == I8_MAX
        assert i16::max() == I16_MAX
        assert i32::max() == I32_MAX
        assert i64::max() == I64_MAX
        assert i128::max() == I128_MAX
        assert i256::max() == I256_MAX
    }

    pub fn get_u8_min() -> u8 {
        return u8(0)
    }
    pub fn get_u8_const_min() -> u8 {
        return U8_MIN
    }

    pub fn get_u16_min() -> u16 {
        return u16(0)
    }

    pub fn get_u16_const_min() -> u16 {
        return U16_MIN
    }

    pub fn get_u32_min() -> u32 {
        return u32(0)
    }

    pub fn get_u32_const_min() -> u32 {
        return U32_MIN
    }

    pub fn get_u64_min() -> u64 {
        return u64(0)
    }

    pub fn get_u64_const_min() -> u64 {
        return U64_MIN
    }

    pub fn get_u128_min() -> u128 {
        return u128(0)
    }

    pub fn get_u128_const_min() -> u128 {
        return U128_MIN
    }

    pub fn get_u256_min() -> u256 {
        return u256(0)
    }

    pub fn get_u256_const_min() -> u256 {
        return U256_MIN
    }

    pub fn get_i8_min() -> i8 {
        return i8(-128)
    }

    pub fn get_i8_const_min() -> i8 {
        return I8_MIN
    }

    pub fn get_i16_min() -> i16 {
        return i16(-32768)
    }

    pub fn get_i16_const_min() -> i16 {
        return I16_MIN
    }

    pub fn get_i32_min() -> i32 {
        return i32(-2147483648)
    }

    pub fn get_i32_const_min() -> i32 {
        return I32_MIN
    }

    pub fn get_i64_min() -> i64 {
        return i64(-9223372036854775808)
    }

    pub fn get_i64_const_min() -> i64 {
        return I64_MIN
    }

    pub fn get_i128_min() -> i128 {
        return i128(-170141183460469231731687303715884105728)
    }

    pub fn get_i128_const_min() -> i128 {
        return I128_MIN
    }

    pub fn get_i256_min() -> i256 {
        return i256(-57896044618658097711785492504343953926634992332820282019728792003956564819968)
    }

    pub fn get_i256_const_min() -> i256 {
        return I256_MIN
    }

    pub fn get_u8_max() -> u8 {
        return u8(255)
    }

    pub fn get_u8_const_max() -> u8 {
        return U8_MAX
    }

    pub fn get_u16_max() -> u16 {
        return u16(65535)
    }

    pub fn get_u16_const_max() -> u16 {
        return U16_MAX
    }

    pub fn get_u32_max() -> u32 {
        return u32(4294967295)
    }

    pub fn get_u32_const_max() -> u32 {
        return U32_MAX
    }

    pub fn get_u64_max() -> u64 {
        return u64(18446744073709551615)
    }

    pub fn get_u64_const_max() -> u64 {
        return U64_MAX
    }

    pub fn get_u128_max() -> u128 {
        return u128(340282366920938463463374607431768211455)
    }

    pub fn get_u128_const_max() -> u128 {
        return U128_MAX
    }

    pub fn get_u256_max() -> u256 {
        return u256(115792089237316195423570985008687907853269984665640564039457584007913129639935)
    }

    pub fn get_u256_const_max() -> u256 {
        return U256_MAX
    }

    pub fn get_i8_max() -> i8 {
        return i8(127)
    }

    pub fn get_i8_const_max() -> i8 {
        return I8_MAX
    }

    pub fn get_i16_max() -> i16 {
        return i16(32767)
    }

    pub fn get_i16_const_max() -> i16 {
        return I16_MAX
    }

    pub fn get_i32_max() -> i32 {
        return i32(2147483647)
    }

    pub fn get_i32_const_max() -> i32 {
        return I32_MAX
    }

    pub fn get_i64_max() -> i64 {
        return i64(9223372036854775807)
    }

    pub fn get_i64_const_max() -> i64 {
        return I64_MAX
    }

    pub fn get_i128_max() -> i128 {
        return i128(170141183460469231731687303715884105727)
    }

    pub fn get_i128_const_max() -> i128 {
        return I128_MAX
    }

    pub fn get_i256_max() -> i256 {
        return i256(57896044618658097711785492504343953926634992332820282019728792003956564819967)
    }

    pub fn get_i256_const_max() -> i256 {
        return I256_MAX
    }
}
