contract Foo:

    pub fn bar():

        # Fe doesn't allow casting from i8 to u16 directly because depending on the order
        # in which sign and size are changed one does arrive at a different value as the
        # following code demonstrates.
        # This is in line with Solidity: https://docs.soliditylang.org/en/latest/080-breaking-changes.html#new-restrictions
        #
        # Notice that Rust does allow the transition in one
        # step and apparently size is changed before the sign:
        # https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cfc82437a365ca1f534a40f5182bd1e2

        let a: i8 = i8(-1)
        let a1: i16 = i16(a)
        let a2: u16 = u16(a1)

        assert a2 == u16(65535)

        let b: i8 = i8(-1)
        let b1: u8 = u8(b)
        let b2: u16 = u16(b1)

        assert b2 == u16(255)