contract Ownable:
  _owner: address

  event OwnershipTransferred:
    idx previousOwner: address
    idx newOwner: address

  pub fn __init__():
    self._owner = msg.sender

  pub fn owner() -> address:
    return self._owner

  pub fn renounceOwnership():
    assert msg.sender == self._owner
    self._owner = address(0)
    emit OwnershipTransferred(previousOwner=msg.sender, newOwner=address(0))

  pub fn transferOwnership(newOwner: address):
    assert msg.sender == self._owner
    assert newOwner != address(0)
    self._owner = newOwner
    emit OwnershipTransferred(previousOwner=msg.sender, newOwner)
