contract Foo:
    pub fn coinbase() -> address:
        return block.coinbase

    pub fn difficulty() -> u256:
        return block.difficulty

    pub fn number() -> u256:
        return block.number

    pub fn timestamp() -> u256:
        return block.timestamp

    pub fn chainid() -> u256:
        return chain.id

    pub fn sender() -> address:
        return msg.sender

    pub fn value() -> u256:
        return msg.value

    pub fn origin() -> address:
        return tx.origin

    pub fn gas_price() -> u256:
        return tx.gas_price
