struct OtherError {
    pub msg: u256
    pub val: bool
}

contract Foo {
    my_other_error: OtherError

    pub fn bar() -> u256 {
        revert
    }

    pub fn revert_custom_error(mut ctx: Context) {
        ctx.send_value(to: address(0), wei: 100)
    }

    pub fn revert_other_error() {
        revert OtherError(msg: 1, val: true)
    }

    pub fn revert_other_error_from_sto(mut self) {
        self.my_other_error = OtherError(msg: 1, val: true)
        revert self.my_other_error.to_mem()
    }
}
