struct Error:
    msg: u256
    val: bool

struct OtherError:
    msg: u256
    val: bool

contract Foo:
    my_other_error: OtherError

    pub fn bar() -> u256:
        revert

    pub fn revert_custom_error():
        revert Error(msg=1, val=true)

    pub fn revert_other_error():
        revert OtherError(msg=1, val=true)

    pub fn revert_other_error_from_sto(self):
        self.my_other_error = OtherError(msg=1, val=true)
        revert self.my_other_error.to_mem()
