struct Error:
    msg: u256
    val: bool

struct OtherError:
    msg: u256
    val: bool

contract Foo:
    my_other_error: OtherError

    pub def bar() -> u256:
        revert

    pub def revert_custom_error():
        revert Error(msg=1, val=true)

    pub def revert_other_error():
        revert OtherError(msg=1, val=true)

    pub def revert_other_error_from_sto():
        self.my_other_error = OtherError(msg=1, val=true)
        revert self.my_other_error.to_mem()
