contract Foo {
    pub fn bar(input: u256) -> u256 {
        return 1 if input > 5 else revert_u256()
    }

    fn revert_u256() -> u256 {
        revert
        return 0
    }

    fn revert_bool() -> bool {
        revert
        return true
    }

    pub fn short_circuit_and(let_through: bool) -> bool {
        return let_through and revert_bool()
    }

    pub fn short_circuit_or(break_early: bool) -> bool {
        return break_early or revert_bool()
    }
}
