contract Foo:
    num: u256
    nums: u256[42]
    str: String<26>

    event MyEvent:
        num: u256
        nums: u256[42]
        str: String<26>

    pub fn write_num(x: u256):
        self.num = x

    pub fn read_num() -> u256:
        return self.num

    pub fn write_nums(x: u256[42]):
        self.nums = x

    pub fn read_nums() -> u256[42]:
        return self.nums.to_mem()

    pub fn write_str(x: String<26>):
        self.str = x

    pub fn read_str() -> String<26>:
        return self.str.to_mem()

    pub fn emit_event():
        emit MyEvent(
            num=self.num,
            nums=self.nums.to_mem(),
            str=self.str.to_mem()
        )