struct House:
    price: u256
    size: u256
    rooms: u8
    vacant: bool

contract Foo:
    my_house: House

    pub fn create_house(self):
        self.my_house = House(
            price=1,
            size=2,
            rooms=u8(5),
            vacant=false
        )
        assert self.my_house.price == 1
        assert self.my_house.size == 2
        assert self.my_house.rooms == u8(5)
        assert self.my_house.vacant == false
        # We change only the size and check other fields are unchanged
        self.my_house.size = 50
        assert self.my_house.size == 50
        assert self.my_house.price == 1
        assert self.my_house.rooms == u8(5)
        assert self.my_house.vacant == false
        # We change only the price and check other fields are unchanged
        self.my_house.price = 1000
        assert self.my_house.size == 50
        assert self.my_house.price == 1000
        assert self.my_house.rooms == u8(5)
        assert self.my_house.vacant == false
        self.my_house.vacant = true
        assert self.my_house.size == 50
        assert self.my_house.price == 1000
        assert self.my_house.rooms == u8(5)
        assert self.my_house.vacant
        self.my_house.rooms = u8(100)
        assert self.my_house.size == 50
        assert self.my_house.price == 1000
        assert self.my_house.rooms == u8(100)
        assert self.my_house.vacant

    pub fn bar() -> u256:
        let building: House = House(
            price=300,
            size=500,
            rooms=u8(20),
            vacant=true
        )
        assert building.size == 500
        assert building.price == 300
        assert building.rooms == u8(20)
        assert building.vacant

        building.vacant = false
        building.price = 1
        building.size = 2
        building.rooms = u8(10)

        assert building.vacant == false
        assert building.price == 1
        assert building.size == 2
        assert building.rooms == u8(10)
        return building.size

    pub fn encode_house() -> u8[128]:
        let house: House = House(
            price=300,
            size=500,
            rooms=u8(20),
            vacant=true
        )
        return house.abi_encode()

    pub fn hashed_house() -> u256:
        let house: House = House(
            price=300,
            size=500,
            rooms=u8(20),
            vacant=true
        )
        return keccak256(house.abi_encode())
