contract Foo:
    other: Bar

    pub fn __init__(self):
        self.other = Bar.create(0)

    pub fn foo(self) -> u256:
        self.other.set_foo_addr(self.address)
        return self.other.answer()

    pub fn add(x: u256, y: u256) -> u256:
        return x + y

contract Bar:
    other: Foo

    pub fn set_foo_addr(self, addr: address):
        self.other = Foo(addr)

    pub fn answer(self) -> u256:
        return self.other.add(20, 22)
