use bar::baz::Baz
use bing::Bing as Bong
use bing::get_42_backend
use ding::{dang::Dang as Dung, dong}
use bing::BingContract

contract Foo:
    pub fn get_my_baz() -> Baz:
        return Baz(my_bool=true, my_u256=26)

    pub fn get_my_bing() -> Bong:
        return Bong(my_address=address(42))

    pub fn get_42() -> u256:
        return get_42_backend()

    pub fn get_26() -> u256:
        return std::bar::bar::get_26()

    pub fn get_my_dyng() -> dong::Dyng:
        return dong::Dyng(
            my_address=address(8),
            my_u256=42,
            my_i8=-1
        )

    pub fn create_bing_contract() -> u256:
        let bing_contract: BingContract = BingContract.create(0)
        return bing_contract.add(40, 50)