use foo::{Foo, Bar, FooBar}

contract FooBarBing {
    pub fn get_bar() -> Bar {
        return Bar(my_u256: 24)
    }

    pub fn create_foobar_contract(mut ctx: Context) -> u256 {
        let foo_bar: FooBar = FooBar.create(ctx, 0)
        return FooBar::add(40, 50)
    }
}

#test
fn test_all(mut ctx: Context) {
    assert FooBarBing::create_foobar_contract(ctx) == 90
    assert FooBarBing::get_bar().my_u256 == 24
}