version: 2.1

common: &common
  working_directory: ~/repo

jobs:
  test:
    <<: *common
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: ensure nightly is default and upgrade
          command: |
            rustup default nightly
            rustup update
      - run:
          name: test
          command: cargo test --workspace

  wasm-test:
    <<: *common
    docker:
      - image: davesque/rust-wasm
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: ensure nightly is default and upgrade
          command: |
            rustup default nightly
            rustup update
      - run:
          name: test
          command: wasm-pack test --node -- --workspace

  lint:
    <<: *common
    docker:
      # Switch back to rustlang/rust:nightly once this fix propagates:
      # https://github.com/rust-lang/rust-clippy/issues/3448
      - image: davesque/rust-lint
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: update rust toolchains
          command: |
            rustup component add clippy
            rustup update
      - run:
          name: lint
          command: make lint

  coverage:
    <<: *common
    machine: true
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: coverage with tarpaulin
          command: |
            ./coverage.sh --out Xml
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  default:
    jobs:
      - test
      - wasm-test
      - lint
      - coverage
