use std::buf::{MemoryBuffer, MemoryBufferReader, MemoryBufferWriter}
use std::traits::Max

#test
fn test_buf_rw() {
    let mut buf: MemoryBuffer = MemoryBuffer::new(len: 161) 
    let mut writer: MemoryBufferWriter = buf.writer()
    let mut reader: MemoryBufferReader = buf.reader()

    writer.write_u256(value: 42)
    writer.write_u256(value: 42)
    writer.write_u256(value: 26)
    writer.write_u8(value: 26)
    writer.write_u256(value: u256::max())
    writer.write_u128(value: u128::max())
    writer.write_u64(value: u64::max())
    writer.write_u32(value: u32::max())
    writer.write_u16(value: u16::max())
    writer.write_u8(value: u8::max())
    writer.write_u8(value: 0)

    assert reader.read_u256() == 42
    assert reader.read_u256() == 42
    assert reader.read_u256() == 26
    assert reader.read_u8() == 26
    assert reader.read_u256() == u256::max()
    assert reader.read_u128() == u128::max()
    assert reader.read_u64() == u64::max()
    assert reader.read_u32() == u32::max()
    assert reader.read_u16() == u16::max()
    assert reader.read_u8() == u8::max()
    assert reader.read_u8() == 0
}