contract Foo {
    pub fn bar(self) -> u256 {
        let mut my_array: Array<u256, 3> = [0; 3]
        my_array[0] = 5
        my_array[1] = 10
        my_array[2] = 15
        let mut sum: u256 = 0
        for i in my_array {
            sum = sum + i
            if sum == 15 {
                break
            }
        }
        return sum
    }
}


#test
fn test_foo(mut ctx: Context) {
    let foo: Foo = Foo.create(ctx, 0)
    assert foo.bar() == 15
}