pub enum E {
    Var { x: i32, u: i32 },
    Var2(E2)
}

pub enum E2 {
    Var(i32)
}

impl E {
    fn extract_num(self) -> i32 {
        match self {
            Self::Var { x, .. } => x
            Self::Var2(E2::Var(x)) => x
        }
    }
}

pub fn foo(e: E) -> i32 {
    match e {
        E::Var { x, .. } => {
            x
        }
        E::Var2(E2::Var(x)) => {
            x
        }
    }
}