enum Tag {
    Tag1,
    Tag2,
    Tag3
}

fn foo(b1: bool, b2: bool) -> i32 {
    use Tag::*

    let tag = if b1 {
        return 0
    } else if b2 {
        Tag1
    } else {
        Tag3
    }
    
    let b = match tag {
        Tag1 => {
            true
        }

        Tag2 => {
            return 3
        }

        Tag3 => {
            false
        }
    }
    
    if b {
        1
    } else {
        2
    }
}