pub fn factorial(mut num: u32) -> u32 {
    let mut res = 1
    while num > 0 {
        res *= num
        num -= 1
    }

    res
}

pub fn factorial2(mut num: u32) -> u32 {
    let mut res = 1
    while true {
        if num > 1 {
            res *= num
            num -= 1
        } else {
            return res
        }
    }
    
    return res
}


pub fn factorial3(mut num: u32) -> u32 {
    let mut res = 1
    while true {
        num = if num > 1 {
            res *= num
            num - 1
        } else {
            break
        }
    }
    
    res
}