struct MyStruct:
    my_num: u256
    my_num2: u8
    my_bool: bool
    my_addr: address

contract Foo:
    my_addrs: address[5]
    my_u128: u128
    my_string: String<10>
    my_u8s: u8[255]
    my_bool: bool
    my_bytes: bytes[100]

    event MyEvent:
        my_addrs: address[5]
        my_u128: u128
        my_string: String<10>
        my_u8s: u8[255]
        my_bool: bool
        my_bytes: bytes[100]

    pub def set_my_addrs(my_addrs: address[5]):
        self.my_addrs = my_addrs

    pub def get_my_addrs() -> address[5]:
        return self.my_addrs.to_mem()

    pub def set_my_u128(my_u128: u128):
        self.my_u128 = my_u128

    pub def get_my_u128() -> u128:
        return self.my_u128

    pub def set_my_string(my_string: String<10>):
        self.my_string = my_string

    pub def get_my_string() -> String<10>:
        return self.my_string.to_mem()

    pub def set_my_u8s(my_u8s: u8[255]):
        self.my_u8s = my_u8s

    pub def get_my_u8s() -> u8[255]:
        return self.my_u8s.to_mem()

    pub def set_my_bool(my_bool: bool):
        self.my_bool = my_bool

    pub def get_my_bool() -> bool:
        return self.my_bool

    pub def set_my_bytes(my_bytes: bytes[100]):
        self.my_bytes = my_bytes

    pub def get_my_bytes() -> bytes[100]:
        return self.my_bytes.to_mem()

    pub def get_my_struct() -> MyStruct:
        return MyStruct(
            my_num=42,
            my_num2=u8(26),
            my_bool=true,
            my_addr=address(123456)
        )

    pub def mod_my_struct(my_struct: MyStruct) -> MyStruct:
        my_struct.my_num = 12341234
        my_struct.my_num2 = u8(42)
        my_struct.my_bool = false
        my_struct.my_addr = address(9999)
        return my_struct

    pub def emit_my_event():
        emit MyEvent(
            my_addrs=self.my_addrs.to_mem(),
            my_u128=self.my_u128,
            my_string=self.my_string.to_mem(),
            my_u8s=self.my_u8s.to_mem(),
            my_bool=self.my_bool,
            my_bytes=self.my_bytes.to_mem()
        )
