fn return_tuple() -> (address, (u256, u8)) {
    return (address(0), (10, 20))
}

fn return_array() -> Array<u8, 3> {
    return [1, 2, 3]
}

contract Foo {
    pub fn bar(self) -> u256 {
        let tuple: (address, (u256, u8)) = return_tuple()
        return tuple.item1.item0
    }

    pub fn sum_things() -> u8 {
        let x: Array<u8, 3> = return_array()
        return x[0] + x[1] + x[2]
    }
}
