contract Foo {
    pub fn explicit_return_a1() {
        return
    }

    pub fn explicit_return_a2() {
        return ()
    }

    pub fn explicit_return_b1() -> () {
        return
    }

    pub fn explicit_return_b2() -> () {
        return ()
    }

    pub fn implicit_a1() {}

    pub fn implicit_a2() -> () {}

    pub fn if_elif_else() -> () {
        if true {
            return ()
        } else if false {
            return
        } else {

        }
    }

    pub fn tuple_stmt() {
        ()
    }
}
