contract Foo:
  pub fn explicit_return_a1():
    return

  pub fn explicit_return_a2():
    return ()

  pub fn explicit_return_b1() -> ():
    return

  pub fn explicit_return_b2() -> ():
    return ()

  pub fn implicit_a1():
    pass

  pub fn implicit_a2() -> ():
    pass

  pub fn if_elif_else() -> ():
    if true:
        return ()
    elif false:
        return
    else:
        pass

  pub fn tuple_stmt():
    ()