pub struct EmptyStruct {

}

/// DocComment1
#attr
// normal comment
/// DocComment2
pub struct StructAttr {
    x: foo::Bar
    y: i32
}

#Event
pub struct StructFieldAttr {
    /// `x` is a topic 
    #topic
    x: i32

    y: u32
}

struct StructWithTupleField {
    x: (i32, u32)
    y: (
        i32,
        foo::Bar,
        u32
    )
    z: ()
}

pub struct StructWithGenericParam<S, T, U> {
    x: S
    y: T
    z: U
}
 
pub struct StructWithGenericParam2<
    S,
    T: foo::Trait,
    U
> {
    x: *(S, *i32)
    y: T
    z: U
}

pub struct StructWithGenericParam3<
    S: foo::Trait + bar::Trait,
    T,
    U: bar::Trait
> {
    x: S
    y: T
    z: U
}