contract Ownable:
  _owner: address
  
  event OwnershipTransferred:
    idx previousOwner: address
    idx newOwner: address
    
  def __init__():
    self._owner = msg.sender
  
  pub def owner() -> address:
    return self._owner
  
  pub def renounceOwnership():
    assert msg.sender == owner
    _owner = address(0)
    emit OwnershipTransferred(msg.sender, address(0))
  
  pub def transferOwnership(newOwner: address):
    assert msg.sender == owner
    assert newOwner != address(0)
    _owner = newOwner
    emit OwnershipTransferred(msg.sender, newOwner)
