contract Foo:
    pub def coinbase() -> address:
        return block.coinbase

    pub def difficulty() -> u256:
        return block.difficulty

    pub def number() -> u256:
        return block.number

    pub def timestamp() -> u256:
        return block.timestamp

    pub def chainid() -> u256:
        return chain.id

    pub def sender() -> address:
        return msg.sender

    pub def value() -> u256:
        return msg.value

    pub def origin() -> address:
        return tx.origin

    pub def gas_price() -> u256:
        return tx.gas_price
