contract Foo:
    num: u256
    nums: u256[42]
    str: string26

    event MyEvent:
        num: u256
        nums: u256[42]
        str: string26

    pub def write_num(x: u256):
        self.num = x

    pub def read_num() -> u256:
        return self.num

    pub def write_nums(x: u256[42]):
        self.nums = x

    pub def read_nums() -> u256[42]:
        return self.nums

    pub def write_str(x: string26):
        self.str = x

    pub def read_str() -> string26:
        return self.str

    pub def emit_event():
        emit MyEvent(self.num, self.nums, self.str)