struct House:
    price: u256
    size: u256
    vacant: bool

contract Foo:
    my_house: House

    pub def create_house():
        self.my_house = House(price=1, size=2, vacant=false)
        assert self.my_house.price == 1
        assert self.my_house.size == 2
        assert self.my_house.vacant == false
        # We change only the size and check other fields are unchanged
        self.my_house.size = 50
        assert self.my_house.size == 50
        assert self.my_house.price == 1
        assert self.my_house.vacant == false
        # We change only the price and check other fields are unchanged
        self.my_house.price = 1000
        assert self.my_house.size == 50
        assert self.my_house.price == 1000
        assert self.my_house.vacant == false



    pub def bar() -> u256:
        building: House = House(price=300, size=500, vacant=true)
        assert building.size == 500
        assert building.price == 300
        assert building.vacant

        building.vacant = false
        building.price = 1
        building.size = 2

        assert building.vacant == false
        assert building.price == 1
        assert building.size == 2
        return building.size
