contract Foo:
    my_num: u256

    pub def add(a: u256, b: u256) -> u256:
        a += b
        return a

    pub def sub(a: u256, b: u256) -> u256:
        a -= b
        return a

    pub def mul(a: u256, b: u256) -> u256:
        a *= b
        return a

    pub def div(a: u256, b: u256) -> u256:
        a /= b
        return a

    pub def mod(a: u256, b: u256) -> u256:
        a %= b
        return a

    pub def pow(a: u256, b: u256) -> u256:
        a **= b
        return a

    pub def lshift(a: u8, b: u8) -> u8:
        a <<= b
        return a

    pub def rshift(a: u8, b: u8) -> u8:
        a >>= b
        return a

    pub def bit_or(a: u8, b: u8) -> u8:
        a |= b
        return a

    pub def bit_xor(a: u8, b: u8) -> u8:
        a ^= b
        return a

    pub def bit_and(a: u8, b: u8) -> u8:
        a &= b
        return a

    pub def add_from_sto(a: u256, b: u256) -> u256:
        self.my_num = a
        self.my_num += b
        return self.my_num

    pub def add_from_mem(a: u256, b: u256) -> u256:
        my_array: u256[10]
        my_array[7] = a
        my_array[7] += b
        return my_array[7]
